### PR TITLE
Support for peer hostAliases in create and update

### PR DESCRIPTION
**Pull request by minollo**
- Let users specify host aliases, so that /etc/hosts on peer containers can be easily managed. Peers need to be able to resolve the ordering node names - needed when using Istio and no real DNS.
- Introduce peer update command - for now to let users change host aliases even after the peer has been created.

### CODE REVIEW

**Comment by adityajoshi12** [comment]
Q: updating the /etc/hosts file is not a good way, let's think of a better way to enable communication between peers and orderer, Kubernetes services could be one of the ways.

**Comment by minollo** [comment]
Surely not something you would want to use in production systems; but it is something which makes testing/prototyping with k8s/istio clusters where nodes are private easy.
Using k8s hostAliases - as I did here - it abstracts users from what happens (/etc/hosts) under the cover.

**Comment by dviejokfs** [comment]
Thanks for the PR!
Could you implement the same for the orderer nodes?

Also, please, you need to complete the DCO; you can execute the following commands to resolve it:
```bash
git rebase --signoff HEAD~10
git push --force
```

**Comment by minollo** [comment]
Sure, I'll do the same for ordering nodes tomorrow.
I have executed the git commands you suggested.

**Comment by minollo** [comment]
Added hostAliases support to ordnodes.
The code base seems to be in dire need of UTs...

**Review by dviejokfs — APPROVED** [review]

**Comment by dviejokfs** [comment]
I'm merging the PR, thank you so much @minollo!

**Pull request merged**
