### PR TITLE
included external hosts as part CSR hosts for peer

### PR DESCRIPTION
**Pull request by adityajoshi12**

### CODE REVIEW

**Comment by dviejokfs** [comment]
Hi @adityajoshi12 , thanks for the PR!

Can you elaborate on why this is needed?

Thank you

**Comment by adityajoshi12** [comment]
> Hi @adityajoshi12 , thanks for the PR!
> 
> Can you elaborate on why this is needed?
> 
> Thank you

When using `istio` the FQDN was not part of `csrHost`, this will ensure that even in the case of a change of Node IPs, CA can be still accessed via the FQDN.

**Comment by dviejokfs** [comment]
But the change is for the peer right?

**Comment by dviejokfs** [comment]
Merged

**Pull request merged**
